name: gen_expects
description: Code generator that walks the widget tree of the test app and outputs expect statements for widget tests.
version: 0.2.2
repository: https://github.com/buttonsrtoys/gen_expects
issue_tracker: https://github.com/buttonsrtoys/gen_expects/issues

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false