name: gen_expects
description: Code generator for widget test expect statements

version: 0.0.2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^5.13.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false