name: gen_expects
description: Code generator for testing expect statements.
version: 0.1.0
repository: https://github.com/buttonsrtoys/gen_expects
issue_tracker: https://github.com/buttonsrtoys/gen_expects/issues

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^4.2.0
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false